version: "3.8"

services:
  api:
    build: ./api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - mynetwork

  front:
    build: ./front
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
